# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$HOME/.cargo/bin:$PATH:$HOME/dev/Android/Sdk/platform-tools:$HOME/dev/Android/Sdk/tools/bin:$HOME/.local/bin

# Path to your oh-my-zsh installation.
export ZSH="/home/yorcun/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias cat="bat"
alias ls="exa"
alias vi="nvim"

##### Google Drive
LOCAL_SYNC_DIR=/home/yorcun/Documents/drive-synced
REMOTE_SYNC_DIR="Drive:"
LOCAL_TODO=$LOCAL_SYNC_DIR/Todo.xlsx
REMOTE_TODO="$REMOTE_SYNC_DIR/Todo.xlsx"
LOCAL_S_TABLE=$LOCAL_SYNC_DIR/"Spaced Repetition Çizelge.xlsx"
REMOTE_S_TABLE="$REMOTE_SYNC_DIR/Spaced Repetition Çizelge.xlsx"
function push-todo() {
  rclone sync $LOCAL_TODO $REMOTE_SYNC_DIR
}

function push-s-table() {
  rclone sync $LOCAL_S_TABLE $REMOTE_SYNC_DIR
}

function pull-todo() {
  rclone sync $REMOTE_TODO $LOCAL_SYNC_DIR
}

function pull-s-table() {
  rclone sync $REMOTE_S_TABLE $LOCAL_SYNC_DIR
}

function pull-kadın-doğum() {
  rclone sync $LOCAL_SYNC_DIR/Kadın\ Doğum Drive:/Kadın\ Doğum
}

##### Visual editor
export VISUAL="code"

##### Functions
ERROR_PREFIX="[ERROR]"
SUCCESS_PREFIX="[SUCCESS]"
function countdown(){
   date1=$((`date +%s` + $1));
   while [ "$date1" -ge `date +%s` ]; do
     echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
     sleep 0.5
   done
   notify-send "Ara" "Çok yoruldun haydi ara ver."
   mpv ~/Music/Old-alarm-clock-sound.mp3
}

function set-wallpaper() {
  if [[ -e "$1" ]]; then
    cp "$1" "$HOME/Pictures/wallpapers/wall"
    feh --bg-fill "$1"
    echo "$SUCCESS_PREFIX Wallpaper set."
  else
    echo "$ERROR_PREFIX File does not exists."
  fi
}


##### AUTOCOMPLETE
COMPLETION_FILE_DIR="$HOME/.dotfiles/zsh/completion"
fpath=($COMPLETION_FILE_DIR $fpath)
autoload -U compinit && compinit

##### GENIUS
export GENIUS_CLIENT_ACCESS_TOKEN="qiJJloKVkr7onXkEh1H1zgfDcVZvRjVzmpPJfvo25c_bV3XDqoPrSY-gjD-7V2_K"
